name: CD

on:
  push:
    branches: [ main ]
    paths:
      - 'VERSION'
    tags-ignore:
      - '**'

jobs:
  release:
    uses: jeffersonlab/container-workflows/.github/workflows/gh-release.yml@v2
    secrets: inherit

  docker_publish:
    needs:
      - release
    uses: jeffersonlab/container-workflows/.github/workflows/docker-publish.yml@v2
    with:
      semvertag: ${{ needs.release.outputs.semvertag }}
    secrets: inherit
